version: '3'
services:
  example_db:
    image: mysql:5.7
    container_name: example_db
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aieububsnlVUOBWHLEINA # any random string will do
      MYSQL_DATABASE: wp_database # the name of your mysql database
      MYSQL_USER: wp_user # the name of the database user
      MYSQL_PASSWORD: password # the password of the mysql user

  example:
    depends_on:
      - example_db
    image: wordpress:latest
    container_name: example
    ports:
      - "1234:80"
    restart: always
    links:
      - example_db:mysql
    volumes:
      - ./wp:/var/www/html
      # - ./wp-content:/var/www/html/wp-content
  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./docker/nginx/conf.d:/etc/nginx/conf.d
     - ./wp:/var/www/html
     - ./database/data:/var/lib/mysql
     - ./database/initdb.d:/docker-entrypoint-initdb.d
    #  - ./database/data:/var/lib/mysql
    #  - ./database/initdb.d:/docker-entrypoint-initdb.d
    links:
     - example
  
  php:
    depends_on:
      - example_db
    build: ./docker/php
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./wp:/var/www/html
    links:
      - example
      - example_db:mysql